language: python
python:
  - "2.7"
install:
  - pip install -U platformio
cache:
  directories:
    - "~/.platformio"
    - "$TRAVIS_BUILD_DIR/.piolibdeps"

script:
  - python travis.py
  - platformio run -e $BUILD_TARGET

matrix:
  fast_finish: true
  include:
  - env: BUILD_TARGET=livingroom
  - env: BUILD_TARGET=livingroom8266
  - env: BUILD_TARGET=custombmp180
  - env: BUILD_TARGET=fastled
    if: branch = dev AND type = push
